version: "3"

services:
  backend:
    build:
      context: backend/.
    image: apg-backend
    container_name: apg_backend
    depends_on:
      - postgres
      - redis
    environment:
      - GOOGLE_API_KEY=${YOUTUBE_DATA_API_KEY}
      - GOOGLE_ADS_PATH_TO_CONFIG=/google-ads.yaml
      - GOOGLE_APPLICATION_CREDENTIALS=/service-account.json
      - DB_HOST=apg_db
      - DB_PORT=5432
      - DB_USER=apg
      - DB_PASSWORD=abc123
      - DB_NAME=apg
      - REDIS_HOST=redis
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - GOOGLE_ADS_API_VERSION=v19
    ports:
      - "5000:5000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5000"]
        interval: 30s
        timeout: 10s
        retries: 5
    network_mode: "host"
    volumes:
      - "${GOOGLE_ADS_YAML:-$HOME/google-ads.yaml}:/google-ads.yaml"
      - "${GOOGLE_APPLICATION_CREDENTIALS}:/service-account.json"
    restart: unless-stopped
  scheduler:
    build:
      context: scheduler/.
    image: apg-scheduler
    container_name: apg_scheduler
    environment:
      - API_HOST=localhost:5000
    depends_on:
      - backend
    network_mode: "host"
    restart: unless-stopped
  postgres:
    image: postgres:9.6
    container_name: apg_db
    environment:
      - POSTGRES_USER=apg
      - POSTGRES_PASSWORD=abc123
    ports:
      - "54321:5432"
    volumes:
      - apg_data:/var/lib/postgresql/data
    network_mode: "host"
    restart: unless-stopped
  redis:
    image: redis:alpine
    ports:
      - "63791:6379"
    network_mode: "host"

volumes:
  apg_data: {}
