# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runtime: python39
entrypoint: gunicorn -b :$PORT server:app --timeout 0 --workers 2

runtime_config:
  python_version: 3

#basic_scaling:
#  max_instances: 1
automatic_scaling:
#  min_instances: 0
  max_instances: 1
instance_class: F4
# choose instance class and scaling type based on needed processing time and memory amount:
# instance classes and free tier quotas (don't forget to adjust gunicorn's --workers flag)::
#   F1: 256MB / 600MHz - 28 free hours per day (default)
#   F2: 512MB / 1.2GHz - 14 free hours per day
#   F4: 1024MB / 2.4GHz - 7 free hours per day
#   B1: 256MB / 600MHz - 9 free hours per day
#   B2: 512MB / 1.2GHz - 4:30 free hours per day (default)
#   B4: 1024MB / 2.4GHz - 2:15 free hours per day
# request timeout:
#   F - 10 minutes (automatic scaling)
#   B - 24 hours (basic scaling)
